# Generated by Django 2.2.9 on 2020-05-30 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quran', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='root',
            name='ayas',
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='word',
            name='aya',
        ),
        migrations.RemoveField(
            model_name='word',
            name='lemma',
        ),
        migrations.RemoveField(
            model_name='word',
            name='root',
        ),
        migrations.RemoveField(
            model_name='word',
            name='sura',
        ),
        migrations.RenameField(
            model_name='aya',
            old_name='text',
            new_name='arabic',
        ),
        migrations.RenameField(
            model_name='translatedaya',
            old_name='text',
            new_name='english',
        ),
        migrations.AddField(
            model_name='translatedaya',
            name='transliteration',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='Lemma',
        ),
        migrations.DeleteModel(
            name='Root',
        ),
        migrations.DeleteModel(
            name='Word',
        ),
    ]
